- hosts: "late-night-studio-instance"
  vars:
    vncserver_password: defaults

  tasks:
    - name: install tigervnc server
      apt:
        name:
          - fvwm
          - xterm
          - xfce4
          - xfce4-goodies
          - gnome-session
          - tigervnc-standalone-server
          - tigervnc-common
        update_cache: true

    - name: create vnc home directory
      file:
        name: ~/.vnc
        state: directory

    - name: setup tigervnc password
      shell: echo {{ vncserver_password }} | vncpasswd -f > ~/.vnc/passwd

    - name: config tigervnc
      copy:
        src: files/xstartup
        dest: ~/.vnc/xstartup
        mode: 0700


    - name: add obs studio repository
      apt_repository:
        repo: ppa:obsproject/obs-studio

    - name: install obs studio and
      apt:
        name:
          - obs-studio
          - chromium-browser
          - git
          - xvfb

    - name: install chrome browser
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: clone jitsi-pop cyberland fork
      git:
        repo: https://github.com/CyberLandConf/jitsi-pop.git
        dest: /root/jitsi-pop


    # - name: start tigervnc
    #   shell: vncserver -passwd /root/.vnc/passwd -xstartup /root/.vnc/xstartup
